<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
<title>Source code</title>
<link rel="stylesheet" type="text/css" href="../../../../../../stylesheet.css" title="Style">
</head>
<body>
<div class="sourceContainer">
<pre><span class="sourceLineNo">001</span>/*<a name="line.1"></a>
<span class="sourceLineNo">002</span> * Licensed to the Apache Software Foundation (ASF) under one<a name="line.2"></a>
<span class="sourceLineNo">003</span> * or more contributor license agreements.  See the NOTICE file<a name="line.3"></a>
<span class="sourceLineNo">004</span> * distributed with this work for additional information<a name="line.4"></a>
<span class="sourceLineNo">005</span> * regarding copyright ownership.  The ASF licenses this file<a name="line.5"></a>
<span class="sourceLineNo">006</span> * to you under the Apache License, Version 2.0 (the<a name="line.6"></a>
<span class="sourceLineNo">007</span> * "License"); you may not use this file except in compliance<a name="line.7"></a>
<span class="sourceLineNo">008</span> * with the License.  You may obtain a copy of the License at<a name="line.8"></a>
<span class="sourceLineNo">009</span> *<a name="line.9"></a>
<span class="sourceLineNo">010</span> *     http://www.apache.org/licenses/LICENSE-2.0<a name="line.10"></a>
<span class="sourceLineNo">011</span> *<a name="line.11"></a>
<span class="sourceLineNo">012</span> * Unless required by applicable law or agreed to in writing, software<a name="line.12"></a>
<span class="sourceLineNo">013</span> * distributed under the License is distributed on an "AS IS" BASIS,<a name="line.13"></a>
<span class="sourceLineNo">014</span> * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.<a name="line.14"></a>
<span class="sourceLineNo">015</span> * See the License for the specific language governing permissions and<a name="line.15"></a>
<span class="sourceLineNo">016</span> * limitations under the License.<a name="line.16"></a>
<span class="sourceLineNo">017</span> */<a name="line.17"></a>
<span class="sourceLineNo">018</span>package org.apache.hadoop.hbase.exceptions;<a name="line.18"></a>
<span class="sourceLineNo">019</span><a name="line.19"></a>
<span class="sourceLineNo">020</span>import java.io.EOFException;<a name="line.20"></a>
<span class="sourceLineNo">021</span>import java.io.IOException;<a name="line.21"></a>
<span class="sourceLineNo">022</span>import java.io.SyncFailedException;<a name="line.22"></a>
<span class="sourceLineNo">023</span>import java.lang.reflect.UndeclaredThrowableException;<a name="line.23"></a>
<span class="sourceLineNo">024</span>import java.net.ConnectException;<a name="line.24"></a>
<span class="sourceLineNo">025</span>import java.net.SocketTimeoutException;<a name="line.25"></a>
<span class="sourceLineNo">026</span>import java.nio.channels.ClosedChannelException;<a name="line.26"></a>
<span class="sourceLineNo">027</span>import java.util.Set;<a name="line.27"></a>
<span class="sourceLineNo">028</span>import java.util.concurrent.TimeoutException;<a name="line.28"></a>
<span class="sourceLineNo">029</span>import org.apache.hadoop.hbase.CallDroppedException;<a name="line.29"></a>
<span class="sourceLineNo">030</span>import org.apache.hadoop.hbase.CallQueueTooBigException;<a name="line.30"></a>
<span class="sourceLineNo">031</span>import org.apache.hadoop.hbase.DoNotRetryIOException;<a name="line.31"></a>
<span class="sourceLineNo">032</span>import org.apache.hadoop.hbase.MultiActionResultTooLarge;<a name="line.32"></a>
<span class="sourceLineNo">033</span>import org.apache.hadoop.hbase.NotServingRegionException;<a name="line.33"></a>
<span class="sourceLineNo">034</span>import org.apache.hadoop.hbase.RegionTooBusyException;<a name="line.34"></a>
<span class="sourceLineNo">035</span>import org.apache.hadoop.hbase.RetryImmediatelyException;<a name="line.35"></a>
<span class="sourceLineNo">036</span>import org.apache.hadoop.hbase.ipc.CallTimeoutException;<a name="line.36"></a>
<span class="sourceLineNo">037</span>import org.apache.hadoop.hbase.ipc.FailedServerException;<a name="line.37"></a>
<span class="sourceLineNo">038</span>import org.apache.hadoop.hbase.quotas.RpcThrottlingException;<a name="line.38"></a>
<span class="sourceLineNo">039</span>import org.apache.hadoop.ipc.RemoteException;<a name="line.39"></a>
<span class="sourceLineNo">040</span>import org.apache.yetus.audience.InterfaceAudience;<a name="line.40"></a>
<span class="sourceLineNo">041</span>import org.apache.yetus.audience.InterfaceStability;<a name="line.41"></a>
<span class="sourceLineNo">042</span><a name="line.42"></a>
<span class="sourceLineNo">043</span>import org.apache.hbase.thirdparty.com.google.common.collect.ImmutableSet;<a name="line.43"></a>
<span class="sourceLineNo">044</span><a name="line.44"></a>
<span class="sourceLineNo">045</span>@InterfaceAudience.Private<a name="line.45"></a>
<span class="sourceLineNo">046</span>@InterfaceStability.Evolving<a name="line.46"></a>
<span class="sourceLineNo">047</span>public final class ClientExceptionsUtil {<a name="line.47"></a>
<span class="sourceLineNo">048</span><a name="line.48"></a>
<span class="sourceLineNo">049</span>  private ClientExceptionsUtil() {<a name="line.49"></a>
<span class="sourceLineNo">050</span>  }<a name="line.50"></a>
<span class="sourceLineNo">051</span><a name="line.51"></a>
<span class="sourceLineNo">052</span>  public static boolean isMetaClearingException(Throwable cur) {<a name="line.52"></a>
<span class="sourceLineNo">053</span>    cur = findException(cur);<a name="line.53"></a>
<span class="sourceLineNo">054</span><a name="line.54"></a>
<span class="sourceLineNo">055</span>    if (cur == null) {<a name="line.55"></a>
<span class="sourceLineNo">056</span>      return true;<a name="line.56"></a>
<span class="sourceLineNo">057</span>    }<a name="line.57"></a>
<span class="sourceLineNo">058</span>    return !isSpecialException(cur) || (cur instanceof RegionMovedException)<a name="line.58"></a>
<span class="sourceLineNo">059</span>      || cur instanceof NotServingRegionException;<a name="line.59"></a>
<span class="sourceLineNo">060</span>  }<a name="line.60"></a>
<span class="sourceLineNo">061</span><a name="line.61"></a>
<span class="sourceLineNo">062</span>  public static boolean isSpecialException(Throwable cur) {<a name="line.62"></a>
<span class="sourceLineNo">063</span>    return (cur instanceof RegionMovedException || cur instanceof RegionOpeningException<a name="line.63"></a>
<span class="sourceLineNo">064</span>      || cur instanceof RegionTooBusyException || cur instanceof RpcThrottlingException<a name="line.64"></a>
<span class="sourceLineNo">065</span>      || cur instanceof MultiActionResultTooLarge || cur instanceof RetryImmediatelyException<a name="line.65"></a>
<span class="sourceLineNo">066</span>      || cur instanceof CallQueueTooBigException || cur instanceof CallDroppedException<a name="line.66"></a>
<span class="sourceLineNo">067</span>      || cur instanceof NotServingRegionException || cur instanceof RequestTooBigException);<a name="line.67"></a>
<span class="sourceLineNo">068</span>  }<a name="line.68"></a>
<span class="sourceLineNo">069</span><a name="line.69"></a>
<span class="sourceLineNo">070</span>  /**<a name="line.70"></a>
<span class="sourceLineNo">071</span>   * Look for an exception we know in the remote exception: - hadoop.ipc wrapped exceptions - nested<a name="line.71"></a>
<span class="sourceLineNo">072</span>   * exceptions Looks for: RegionMovedException / RegionOpeningException / RegionTooBusyException /<a name="line.72"></a>
<span class="sourceLineNo">073</span>   * RpcThrottlingException<a name="line.73"></a>
<span class="sourceLineNo">074</span>   * @return null if we didn't find the exception, the exception otherwise.<a name="line.74"></a>
<span class="sourceLineNo">075</span>   */<a name="line.75"></a>
<span class="sourceLineNo">076</span>  public static Throwable findException(Object exception) {<a name="line.76"></a>
<span class="sourceLineNo">077</span>    if (exception == null || !(exception instanceof Throwable)) {<a name="line.77"></a>
<span class="sourceLineNo">078</span>      return null;<a name="line.78"></a>
<span class="sourceLineNo">079</span>    }<a name="line.79"></a>
<span class="sourceLineNo">080</span>    Throwable cur = (Throwable) exception;<a name="line.80"></a>
<span class="sourceLineNo">081</span>    while (cur != null) {<a name="line.81"></a>
<span class="sourceLineNo">082</span>      if (isSpecialException(cur)) {<a name="line.82"></a>
<span class="sourceLineNo">083</span>        return cur;<a name="line.83"></a>
<span class="sourceLineNo">084</span>      }<a name="line.84"></a>
<span class="sourceLineNo">085</span>      if (cur instanceof RemoteException) {<a name="line.85"></a>
<span class="sourceLineNo">086</span>        RemoteException re = (RemoteException) cur;<a name="line.86"></a>
<span class="sourceLineNo">087</span>        cur = re.unwrapRemoteException();<a name="line.87"></a>
<span class="sourceLineNo">088</span><a name="line.88"></a>
<span class="sourceLineNo">089</span>        // unwrapRemoteException can return the exception given as a parameter when it cannot<a name="line.89"></a>
<span class="sourceLineNo">090</span>        // unwrap it. In this case, there is no need to look further<a name="line.90"></a>
<span class="sourceLineNo">091</span>        // noinspection ObjectEquality<a name="line.91"></a>
<span class="sourceLineNo">092</span>        if (cur == re) {<a name="line.92"></a>
<span class="sourceLineNo">093</span>          return cur;<a name="line.93"></a>
<span class="sourceLineNo">094</span>        }<a name="line.94"></a>
<span class="sourceLineNo">095</span><a name="line.95"></a>
<span class="sourceLineNo">096</span>        // When we receive RemoteException which wraps IOException which has a cause as<a name="line.96"></a>
<span class="sourceLineNo">097</span>        // RemoteException we can get into infinite loop here; so if the cause of the exception<a name="line.97"></a>
<span class="sourceLineNo">098</span>        // is RemoteException, we shouldn't look further.<a name="line.98"></a>
<span class="sourceLineNo">099</span>      } else if (cur.getCause() != null &amp;&amp; !(cur.getCause() instanceof RemoteException)) {<a name="line.99"></a>
<span class="sourceLineNo">100</span>        cur = cur.getCause();<a name="line.100"></a>
<span class="sourceLineNo">101</span>      } else {<a name="line.101"></a>
<span class="sourceLineNo">102</span>        return cur;<a name="line.102"></a>
<span class="sourceLineNo">103</span>      }<a name="line.103"></a>
<span class="sourceLineNo">104</span>    }<a name="line.104"></a>
<span class="sourceLineNo">105</span><a name="line.105"></a>
<span class="sourceLineNo">106</span>    return null;<a name="line.106"></a>
<span class="sourceLineNo">107</span>  }<a name="line.107"></a>
<span class="sourceLineNo">108</span><a name="line.108"></a>
<span class="sourceLineNo">109</span>  // This list covers most connectivity exceptions but not all.<a name="line.109"></a>
<span class="sourceLineNo">110</span>  // For example, in SocketOutputStream a plain IOException is thrown at times when the channel is<a name="line.110"></a>
<span class="sourceLineNo">111</span>  // closed.<a name="line.111"></a>
<span class="sourceLineNo">112</span>  private static final ImmutableSet&lt;Class&lt;? extends Throwable&gt;&gt; CONNECTION_EXCEPTION_TYPES =<a name="line.112"></a>
<span class="sourceLineNo">113</span>    ImmutableSet.of(SocketTimeoutException.class, ConnectException.class,<a name="line.113"></a>
<span class="sourceLineNo">114</span>      ClosedChannelException.class, SyncFailedException.class, EOFException.class,<a name="line.114"></a>
<span class="sourceLineNo">115</span>      TimeoutException.class, TimeoutIOException.class, CallTimeoutException.class,<a name="line.115"></a>
<span class="sourceLineNo">116</span>      ConnectionClosingException.class, FailedServerException.class,<a name="line.116"></a>
<span class="sourceLineNo">117</span>      ConnectionClosedException.class);<a name="line.117"></a>
<span class="sourceLineNo">118</span><a name="line.118"></a>
<span class="sourceLineNo">119</span>  /**<a name="line.119"></a>
<span class="sourceLineNo">120</span>   * For test only. Usually you should use the {@link #isConnectionException(Throwable)} method<a name="line.120"></a>
<span class="sourceLineNo">121</span>   * below.<a name="line.121"></a>
<span class="sourceLineNo">122</span>   */<a name="line.122"></a>
<span class="sourceLineNo">123</span>  public static Set&lt;Class&lt;? extends Throwable&gt;&gt; getConnectionExceptionTypes() {<a name="line.123"></a>
<span class="sourceLineNo">124</span>    return CONNECTION_EXCEPTION_TYPES;<a name="line.124"></a>
<span class="sourceLineNo">125</span>  }<a name="line.125"></a>
<span class="sourceLineNo">126</span><a name="line.126"></a>
<span class="sourceLineNo">127</span>  /**<a name="line.127"></a>
<span class="sourceLineNo">128</span>   * Check if the exception is something that indicates that we cannot contact/communicate with the<a name="line.128"></a>
<span class="sourceLineNo">129</span>   * server.<a name="line.129"></a>
<span class="sourceLineNo">130</span>   * @param e exception to check<a name="line.130"></a>
<span class="sourceLineNo">131</span>   * @return true when exception indicates that the client wasn't able to make contact with server<a name="line.131"></a>
<span class="sourceLineNo">132</span>   */<a name="line.132"></a>
<span class="sourceLineNo">133</span>  public static boolean isConnectionException(Throwable e) {<a name="line.133"></a>
<span class="sourceLineNo">134</span>    if (e == null) {<a name="line.134"></a>
<span class="sourceLineNo">135</span>      return false;<a name="line.135"></a>
<span class="sourceLineNo">136</span>    }<a name="line.136"></a>
<span class="sourceLineNo">137</span>    for (Class&lt;? extends Throwable&gt; clazz : CONNECTION_EXCEPTION_TYPES) {<a name="line.137"></a>
<span class="sourceLineNo">138</span>      if (clazz.isAssignableFrom(e.getClass())) {<a name="line.138"></a>
<span class="sourceLineNo">139</span>        return true;<a name="line.139"></a>
<span class="sourceLineNo">140</span>      }<a name="line.140"></a>
<span class="sourceLineNo">141</span>    }<a name="line.141"></a>
<span class="sourceLineNo">142</span>    return false;<a name="line.142"></a>
<span class="sourceLineNo">143</span>  }<a name="line.143"></a>
<span class="sourceLineNo">144</span><a name="line.144"></a>
<span class="sourceLineNo">145</span>  /**<a name="line.145"></a>
<span class="sourceLineNo">146</span>   * Translates exception for preemptive fast fail checks.<a name="line.146"></a>
<span class="sourceLineNo">147</span>   * @param t exception to check<a name="line.147"></a>
<span class="sourceLineNo">148</span>   * @return translated exception n<a name="line.148"></a>
<span class="sourceLineNo">149</span>   */<a name="line.149"></a>
<span class="sourceLineNo">150</span>  public static Throwable translatePFFE(Throwable t) throws IOException {<a name="line.150"></a>
<span class="sourceLineNo">151</span>    if (t instanceof NoSuchMethodError) {<a name="line.151"></a>
<span class="sourceLineNo">152</span>      // We probably can't recover from this exception by retrying.<a name="line.152"></a>
<span class="sourceLineNo">153</span>      throw (NoSuchMethodError) t;<a name="line.153"></a>
<span class="sourceLineNo">154</span>    }<a name="line.154"></a>
<span class="sourceLineNo">155</span><a name="line.155"></a>
<span class="sourceLineNo">156</span>    if (t instanceof NullPointerException) {<a name="line.156"></a>
<span class="sourceLineNo">157</span>      // The same here. This is probably a bug.<a name="line.157"></a>
<span class="sourceLineNo">158</span>      throw (NullPointerException) t;<a name="line.158"></a>
<span class="sourceLineNo">159</span>    }<a name="line.159"></a>
<span class="sourceLineNo">160</span><a name="line.160"></a>
<span class="sourceLineNo">161</span>    if (t instanceof UndeclaredThrowableException) {<a name="line.161"></a>
<span class="sourceLineNo">162</span>      t = t.getCause();<a name="line.162"></a>
<span class="sourceLineNo">163</span>    }<a name="line.163"></a>
<span class="sourceLineNo">164</span>    if (t instanceof RemoteException) {<a name="line.164"></a>
<span class="sourceLineNo">165</span>      t = ((RemoteException) t).unwrapRemoteException();<a name="line.165"></a>
<span class="sourceLineNo">166</span>    }<a name="line.166"></a>
<span class="sourceLineNo">167</span>    if (t instanceof DoNotRetryIOException) {<a name="line.167"></a>
<span class="sourceLineNo">168</span>      throw (DoNotRetryIOException) t;<a name="line.168"></a>
<span class="sourceLineNo">169</span>    }<a name="line.169"></a>
<span class="sourceLineNo">170</span>    if (t instanceof Error) {<a name="line.170"></a>
<span class="sourceLineNo">171</span>      throw (Error) t;<a name="line.171"></a>
<span class="sourceLineNo">172</span>    }<a name="line.172"></a>
<span class="sourceLineNo">173</span>    return t;<a name="line.173"></a>
<span class="sourceLineNo">174</span>  }<a name="line.174"></a>
<span class="sourceLineNo">175</span>}<a name="line.175"></a>




























































</pre>
</div>
</body>
</html>
